# Default initial positions for dual_arm's ros2_control fake system

initial_positions:
  fp3_finger_joint1: 0.0350
  fp3_finger_joint2: 0.0350
  fp3_joint1: 0.0
  fp3_joint2: -0.785
  fp3_joint3: 0.0
  fp3_joint4: -2.3560
  fp3_joint5: 0.0
  fp3_joint6: -1.571
  fp3_joint7: 0.785
  fr3_finger_joint1: 0.0350
  fr3_finger_joint2: 0.0350
  fr3_joint1: 0.0
  fr3_joint2: -0.785
  fr3_joint3: 0.0
  fr3_joint4: -2.3560
  fr3_joint5: 0.0
  fr3_joint6: -1.571
  fr3_joint7: 0.785