# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    fr3_moveit_arm:
      type: joint_trajectory_controller/JointTrajectoryController


    fp3_moveit_arm:
      type: joint_trajectory_controller/JointTrajectoryController


    fr3_moviet_hand:
      type: position_controllers/GripperActionController


    fp3_moveit_hand:
      type: position_controllers/GripperActionController


    fr3_moveit:
      type: joint_trajectory_controller/JointTrajectoryController


    fp3_moveit:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

fr3_moveit_arm:
  ros__parameters:
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    command_interfaces:
      - position
      - velocity
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
fp3_moveit_arm:
  ros__parameters:
    joints:
      - fp3_joint1
      - fp3_joint2
      - fp3_joint3
      - fp3_joint4
      - fp3_joint5
      - fp3_joint6
      - fp3_joint7
    command_interfaces:
      - position
      - velocity
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
fr3_moviet_hand:
  ros__parameters:
    joint: fr3_finger_joint1
fp3_moveit_hand:
  ros__parameters:
    joint: fp3_finger_joint1
fr3_moveit:
  ros__parameters:
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
      - fr3_finger_joint1
      - fr3_finger_joint2
    command_interfaces:
      - position
      - velocity
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
fp3_moveit:
  ros__parameters:
    joints:
      - fp3_joint1
      - fp3_joint2
      - fp3_joint3
      - fp3_joint4
      - fp3_joint5
      - fp3_joint6
      - fp3_joint7
      - fp3_finger_joint1
      - fp3_finger_joint2
    command_interfaces:
      - position
      - velocity
      - effort
    state_interfaces:
      - position
      - velocity
      - effort