controller_names:
  - fr3_arm_controller
  - fr3_gripper_controller
 # - hand_controller

fr3_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - fr3_joint1
    - fr3_joint2
    - fr3_joint3
    - fr3_joint4
    - fr3_joint5
    - fr3_joint6
    - fr3_joint7
  
  
fr3_gripper_controller:
  action_ns: gripper_cmd
  type: position_controllers::GripperActionController
  default: true
  joints: 
    - fr3_finger_joint1
    - fr3_finger_joint2
# hand_controller:
#   action_ns: follow_joint_trajectory
#   type: FollowJointTrajectory
#   default: true
#   joints:
#     - fr3_finger_joint1
#     - fr3_finger_joint2
